### ISSUE TITLE
Add me to contribute

### ISSUE THREAD

**Issue by vijay3150** [thegautamkumarjaiswal/IPL-RIP6O#3]
assign me to your contribution in Devincept at # ipl-rip 60

**Comment by thegautamkumarjaiswal** [comment]
@vijay3150  Can you please explain me what are you suppose to tell?

**Comment by vijay3150** [comment]
Sorry i messaged in issues i want to contribute in  to this project by the the way i want to message in pull request i have messaged here

**Comment by thegautamkumarjaiswal** [comment]
> Sorry i messaged in issues i want to contribute in to this project by the the way i want to message in pull request i have messaged here

No problem. Kindly join the #ipl-rip6o channel on devincept workspace on slack.
